# Generated by Django 3.2.7 on 2021-09-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('passage_date', models.DateField(null=True)),
                ('passage_user_id', models.IntegerField(null=True)),
                ('questions', models.ManyToManyField(to='quizes_app.Question')),
            ],
        ),
    ]
