# Generated by Django 3.2.7 on 2021-09-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes_app', '0003_auto_20210930_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateField(),
        ),
    ]
