# Generated by Django 3.2.7 on 2021-09-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes_app', '0004_alter_quiz_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='passage_date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='passage_user_id',
        ),
    ]
