# Generated by Django 3.2.7 on 2021-09-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes_app', '0006_auto_20210930_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice',
            field=models.ManyToManyField(to='quizes_app.Answer'),
        ),
    ]
