# Generated by Django 3.2.7 on 2021-09-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes_app', '0007_auto_20210930_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='answer',
        ),
    ]
